### ISSUE TITLE
Never show gray button, always allow to open lightbox on any URL

### ISSUE THREAD

**Issue by patricksavalle** [mobbr/mobbr-browser-plugin#18]
Lightbox should open on any URL. Always show blue button. The gray button might suggest the plugin is disabled.

Note, that this can already be implemented, but that the lightbox has 'unknown behaviour' _insert twilight theme here_ on non-Mobbrized URL's.

In a future release we should probably add a highlight to the button when a Mobbr enabled URL is detected, like a red dot in the lower right corner or something.

**Comment by patricksavalle** [comment]
See: https://github.com/mobbr/mobbr-lightbox/issues/14

**Comment by jrjackso** [comment]
@patricksavalle If you don't like the '1' for Mobbr enabled URL let me know / set mobbrEnabledUrlBadgeText to empty string. I tried a few unicode dots, etc. and none looked great. Using a space isn't too bad, but the red square looks big (i.e. if you set mobbrEnabledUrlBadgeText to " " (space))
