### ISSUE TITLE
Check for Mobbr support using an API call

### ISSUE THREAD

**Issue by patricksavalle** [mobbr/mobbr-browser-plugin#20]
At the moment the plugin inspects the metadata of a page to determine whether or not the page has Mobbr support.

Mobbr has multiple mechanisms however. The best way to check, is to do an API call. See: https://github.com/mobbr/mobbr-api-v1/tree/master/uris#get-info

Use the 'verbose=false' argument.

The API call can take some time, only use it when no metadata is found and do it asynchronous.

If complex don't include in MVP.

**Comment by jrjackso** [comment]
This seems like a privacy concern.. Thoughts?
The current way looks for a participation element, then if that's not found, locally compares against api_v1/api/api_connections. Unless script-including the mobbr-button sends along a user's URL by default (I don't think so - @handijk?), the plugin doesn't give it up until they click the MOBBR browser action button.  If I call get-info on all of a user's URLs without participation to determine mobbr vs. not, the server is getting every URL a user visits pretty much.

**Comment by patricksavalle** [comment]
Yes, bad idea. (Many extensions work like this however, for instance diigo). Not necessary in the MVP too.
