### ISSUE TITLE
Show number of participants (id's) in button

### ISSUE THREAD

**Issue by patricksavalle** [mobbr/mobbr-browser-plugin#22]
The scripts has a participants array, maybe have the button show the number of ID's. Limit at 2 or 3 digits depending on space available. Show something like 99+ or 999+ when exceeded.

**Comment by jrjackso** [comment]
E.g. https://fastmovingtargets.nl/workforce/653/odeon-de-spiegel-hoe-ziet-het-theater-van-de-toekomst-eruit

![screenshot](https://cloud.githubusercontent.com/assets/2060208/8889659/e7a53536-32b1-11e5-90ba-47713f1499df.png)
