### ISSUE TITLE
Show green icon when money is pledged to current page / URL

### ISSUE THREAD

**Issue by patricksavalle** [mobbr/mobbr-browser-plugin#5]
IF Mobbr support is detected THEN check if money is pledged, if so turn button green.

Aks me for the green button in the comments.

A page has Mobbr support if it has an metadata-script or when it is on a Mobbr supported domain (   /api_v1/api/api_connections), this logic is already in the plugin, since it activate the button.

(Needs an API modification, cannot do this from a plugin yet, call should probably be async too in order not to delay anything)

**Comment by samtechie** [comment]
Hello, This issue is not really clear. If you can elaborate more on the steps you go through and where the green icon appears.

**Comment by patricksavalle** [comment]
Do you have the Chrome plugin installed?

Than for instance on this very URL you will see there is a payment.

**Comment by patricksavalle** [comment]
Hi, do you have the plugin installed? Then you can see that on this very URL an amount is pledged. If an amount is pledged, the button of the plugin (now green with a red 1) should be green.

See:

<img width="1183" alt="screen shot 2015-07-29 at 15 43 15" src="https://cloud.githubusercontent.com/assets/701331/8959038/c75931f6-3608-11e5-9ed3-72eadad86288.png">

If you start working on this issue, I will need to make a slight API modification (add a method where you can check the URL on pledged amounts), so let me know.

**Comment by samtechie** [comment]
To confirm the (red 1) should turn to green if money is pledged. Not the button itself :) Another image, instead of the blue one.

If you start working on this item, I will have to open my photoshop and create a green button for you to use, please let me know.

**Comment by patricksavalle** [comment]
I don't understand :)

What is the question?

**Comment by jrjackso** [comment]
@samtechie 
If you look at a url like
https://mobbr.com/#/task/aHR0cHM6Ly9naXRodWIuY29tL21vYmJyL21vYmJyLWZyb250ZW5kL2lzc3Vlcy8yODU=
at the bottom there are green mobbr icons. I think the intent is to use that color instead of the blue when money has been pledged. The red "1" will stay red, but the blue won't be there - it'll be green.

**Comment by patricksavalle** [comment]
Correct! Thank you.

**Comment by samtechie** [comment]
Yes I understand now the mobbr plugin button should turn green when money is pledged.

**Comment by samtechie** [comment]
@patricksavalle sorry for the delay on this. I want to finish it today so i understand I need a green icon and you need to make an API modification. Let me know when I can proceed.

**Comment by patricksavalle** [comment]
Ok, will do this monday!

**Comment by patricksavalle** [comment]
Hi @samtechie you can use this API call: https://api.mobbr.com/api_v1/balances/uri?url=...

If there is an total_amount (>0) then the button may be green!

If you set the Accept-header in the request to 'application/json' the response will be something like:

```
{
    "result": {
    "balances": [
    {
        "updatedatetime": null,
        "exchange_rate": "0",
        "amount": "0",
        "currency_iso": "EUR",
        "converted_amount": "0",
        "currency_description": "Euro"
    }   
  ],
  "total_amount": "0",
  "total_currency_iso": "EUR"
},
"message": null
}
```

**Comment by samtechie** [comment]
@patricksavalle ok do I need the green button icon?

**Comment by patricksavalle** [comment]
Can you for now use a renamed version of the blue icon? I can replace it with a green version myself once I have photoshop installed again :)

**Comment by davidsemakula** [comment]
@patricksavalle @samtechie should I go ahead and fix this issue? seems to be stagnant.

**Comment by patricksavalle** [comment]
Yes, please do. "Can you for now use a renamed _duplicate_ of the blue icon? I can replace it with a green version myself once I have photoshop installed again :)"

**Comment by samtechie** [comment]
@davidsemakula  Sure its fine.

**Comment by davidsemakula** [comment]
Ok I'm on it.

**Comment by davidsemakula** [comment]
@patricksavalle  Checkout https://github.com/mobbr/mobbr-plugin-chrome/pull/24 for a fix

**Comment by patricksavalle** [comment]
Payment didn't work properly for this one. Probably because the issue was not referenced from the commits. I will pay this one directly.
